export const BARANGAYS = [
    { name: "BRGY. 1", code: "B01" },
    { name: "BRGY. 2", code: "B02" },
    { name: "BRGY. 3", code: "B03" },
    { name: "BRGY. 4", code: "B04" },
    { name: "BRGY. 5", code: "B05" },
    { name: "BRGY. 6", code: "B06" },
    { name: "BRGY. 7", code: "B07" },
    { name: "BRGY. 8", code: "B08" },
    { name: "BRGY. 9", code: "B09" },
    { name: "BRGY. 10", code: "B10" },
    { name: "BRGY. 11", code: "B11" },
    { name: "BRGY. BARRA", code: "BRR" },
    { name: "BRGY. BOCOHAN", code: "BCH" },
    { name: "BRGY. COTTA", code: "COT" },
    { name: "BRGY. DALAHICAN", code: "DAL" },
    { name: "BRGY. DOMOIT", code: "DOM" },
    { name: "BRGY. GULANG-GULANG", code: "GGL" },
    { name: "BRGY. IBABANG DUPAY", code: "IBD" },
    { name: "BRGY. IBABANG IYAM", code: "IBY" },
    { name: "BRGY. IBABANG TALIM", code: "IBT" },
    { name: "BRGY. ILAYANG DUPAY", code: "ILD" },
    { name: "BRGY. ILAYANG IYAM", code: "ILY" },
    { name: "BRGY. ILAYANG TALIM", code: "ILT" },
    { name: "BRGY. ISABANG", code: "ISB" },
    { name: "BRGY. MARKETVIEW", code: "MVS" },
    { name: "BRGY. MAYAO CROSSING", code: "MCR" },
    { name: "BRGY. MAYAO CASTILLO", code: "MCS" },
    { name: "BRGY. MAYAO KANLURAN", code: "MKR" },
    { name: "BRGY. MAYAO PARADA", code: "MPR" },
    { name: "BRGY. MAYAO SILANGAN", code: "MSL" },
    { name: "BRGY. RANSOHAN", code: "RAN" },
    { name: "BRGY. SALINAS", code: "SAL" },
    { name: "BRGY. TALAO-TALAO", code: "TAL" },
];